image: alpine:latest

pages:
    stage: deploy
    script:
        - echo 'Generating index.html...'
        - touch index.html
    artifacts:
        paths:
            - index.html
    only:
        - main
